// A compact list of major US cities for location autocomplete suggestions.
// The location input still accepts free text, so any city not listed can be typed.
export const US_CITIES: string[] = [
  'New York, NY','Los Angeles, CA','Chicago, IL','Houston, TX','Phoenix, AZ','Philadelphia, PA',
  'San Antonio, TX','San Diego, CA','Dallas, TX','San Jose, CA','Austin, TX','Jacksonville, FL',
  'Fort Worth, TX','Columbus, OH','Charlotte, NC','San Francisco, CA','Indianapolis, IN','Seattle, WA',
  'Denver, CO','Washington, DC','Boston, MA','El Paso, TX','Nashville, TN','Detroit, MI',
  'Oklahoma City, OK','Portland, OR','Las Vegas, NV','Memphis, TN','Louisville, KY','Baltimore, MD',
  'Milwaukee, WI','Albuquerque, NM','Tucson, AZ','Fresno, CA','Mesa, AZ','Sacramento, CA',
  'Atlanta, GA','Kansas City, MO','Colorado Springs, CO','Miami, FL','Raleigh, NC','Omaha, NE',
  'Long Beach, CA','Virginia Beach, VA','Oakland, CA','Minneapolis, MN','Tulsa, OK','Tampa, FL',
  'Arlington, TX','New Orleans, LA','Wichita, KS','Cleveland, OH','Bakersfield, CA','Aurora, CO',
  'Anaheim, CA','Honolulu, HI','Santa Ana, CA','Riverside, CA','Corpus Christi, TX','Lexington, KY',
  'Stockton, CA','Henderson, NV','Saint Paul, MN','St. Louis, MO','Cincinnati, OH','Pittsburgh, PA',
  'Greensboro, NC','Anchorage, AK','Plano, TX','Lincoln, NE','Orlando, FL','Irvine, CA',
  'Newark, NJ','Toledo, OH','Durham, NC','Chula Vista, CA','Fort Wayne, IN','Jersey City, NJ',
  'St. Petersburg, FL','Laredo, TX','Madison, WI','Chandler, AZ','Buffalo, NY','Lubbock, TX',
  'Scottsdale, AZ','Reno, NV','Glendale, AZ','Gilbert, AZ','Winston-Salem, NC','North Las Vegas, NV',
  'Norfolk, VA','Chesapeake, VA','Garland, TX','Irving, TX','Hialeah, FL','Fremont, CA',
  'Boise, ID','Richmond, VA','Baton Rouge, LA','Spokane, WA','Des Moines, IA','Tacoma, WA',
  'San Bernardino, CA','Modesto, CA','Fontana, CA','Santa Clarita, CA','Birmingham, AL','Oxnard, CA',
  'Fayetteville, NC','Moreno Valley, CA','Rochester, NY','Glendale, CA','Huntington Beach, CA','Salt Lake City, UT',
  'Grand Rapids, MI','Amarillo, TX','Yonkers, NY','Aurora, IL','Montgomery, AL','Akron, OH',
  'Little Rock, AR','Huntsville, AL','Augusta, GA','Port St. Lucie, FL','Grand Prairie, TX','Columbus, GA',
  'Tallahassee, FL','Overland Park, KS','Tempe, AZ','McKinney, TX','Mobile, AL','Cape Coral, FL',
  'Shreveport, LA','Frisco, TX','Knoxville, TN','Worcester, MA','Brownsville, TX','Vancouver, WA',
  'Fort Lauderdale, FL','Sioux Falls, SD','Ontario, CA','Chattanooga, TN','Providence, RI','Newport News, VA',
  'Rancho Cucamonga, CA','Santa Rosa, CA','Oceanside, CA','Salem, OR','Elk Grove, CA','Garden Grove, CA',
  'Pembroke Pines, FL','Peoria, AZ','Eugene, OR','Corona, CA','Cary, NC','Springfield, MO',
  'Fort Collins, CO','Jackson, MS','Alexandria, VA','Hayward, CA','Clarksville, TN','Lakewood, CO',
  'Lancaster, CA','Salinas, CA','Palmdale, CA','Hollywood, FL','Springfield, MA','Macon, GA',
  'Kansas City, KS','Sunnyvale, CA','Pomona, CA','Killeen, TX','Escondido, CA','Pasadena, TX',
  'Naperville, IL','Bellevue, WA','Joliet, IL','Murfreesboro, TN','Midland, TX','Rockford, IL',
  'Paterson, NJ','Savannah, GA','Bridgeport, CT','Torrance, CA','McAllen, TX','Syracuse, NY',
  'Surprise, AZ','Denton, TX','Roseville, CA','Thornton, CO','Miramar, FL','Pasadena, CA',
  'Mesquite, TX','Olathe, KS','Dayton, OH','Carrollton, TX','Waco, TX','Orange, CA',
  'Fullerton, CA','Charleston, SC','West Palm Beach, FL','Visalia, CA','Hampton, VA','Gainesville, FL',
  'Warren, MI','Coral Springs, FL','Cedar Rapids, IA','Round Rock, TX','Sterling Heights, MI','Kent, WA',
  'Columbia, SC','Santa Clara, CA','New Haven, CT','Stamford, CT','Concord, CA','Elizabeth, NJ',
  'Athens, GA','Thousand Oaks, CA','Lafayette, LA','Simi Valley, CA','Topeka, KS','Norman, OK',
  'Fargo, ND','Wilmington, NC','Abilene, TX','Odessa, TX','Columbia, MO','Pearland, TX',
  'Victorville, CA','Hartford, CT','Vallejo, CA','Allentown, PA','Berkeley, CA','Richardson, TX',
  'Arvada, CO','Ann Arbor, MI','Rochester, MN','Cambridge, MA','Sugar Land, TX','Lansing, MI',
  'Evansville, IN','College Station, TX','Fairfield, CA','Clearwater, FL','Beaumont, TX','Independence, MO',
  'Provo, UT','West Jordan, UT','Murrieta, CA','Palm Bay, FL','El Monte, CA','Carlsbad, CA',
  'North Charleston, SC','Temecula, CA','Clovis, CA','Springfield, IL','Meridian, ID','Westminster, CO',
  'Costa Mesa, CA','High Point, NC','Manchester, NH','Pueblo, CO','Lakeland, FL','Pompano Beach, FL',
  'Boca Raton, FL','Destin, FL','Naples, FL','Sarasota, FL','Bozeman, MT','Asheville, NC',
]
